Fixity Fix?
`samples/Bogdan.TestApp` failed to build with CS0246:

	$ git clone https://github.com/moljac/microsoft-authentication-library-for-dotnet.git msal
	$ cd msal
	$ git checkout trwalke/MultiAccountSample
	$ cd samples/Bogdan.TestApp
	$ msbuild /restore
	…
	  MainActivity.cs(29,17): error CS0246: The type or namespace name 'IMultipleAccountPublicClientApplication' could not be found
	  MainActivity.cs(248,60): error CS0246: The type or namespace name 'IMultipleAccountPublicClientApplicationRemoveAccountCallback' could not be found
	  MainActivity.cs(405,31): error CS0246: The type or namespace name 'IPublicClientApplicationMultipleAccountApplicationCreatedListener' could not be found (are you missing a using directive or an assembly reference?) [/Users/jon/Documents/Developer/src/moljac/msal/samples/Bogdan.TestApp/App1.csproj]
	  MainActivity.cs(407,37): error CS0246: The type or namespace name 'IMultipleAccountPublicClientApplication' could not be found
	  MainActivity.cs(411,24): error CS0246: The type or namespace name 'IMultipleAccountPublicClientApplication' could not be found
	  MainActivity.cs(418,35): error CS0246: The type or namespace name 'IMultipleAccountPublicClientApplication' could not be found

Thus starts the rabbit hole: `IMultipleAccountPublicClientApplication`
can't be found because it wasn't *bound*, because of 6960e456:

	<remove-node path="/api/package[@name='com.microsoft.identity.client']/interface[@name='IPublicClientApplication.LoadAccountsCallback']" />

The removal of the `com.microsoft.identity.client.IPublicClientApplication.LoadAccountsCallback`
type causes other types to be invalidated:

	obj/Debug/monoandroid10.0/api.xml(407, 10) : warning BG8800: Unknown parameter type 'com.microsoft.identity.client.IPublicClientApplication.LoadAccountsCallback' for member 'Com.Microsoft.Identity.Client.IMultipleAccountPublicClientApplication.GetAccounts (com.microsoft.identity.client.IPublicClientApplication.LoadAccountsCallback)'.

which invalidates `IMultipleAccountPublicClientApplication`, etc.

Thus, to ensure that `IMultipleAccountPublicClientApplication`/etc.
are bound, we MUST NOT remove `IPublicClientApplication.LoadAccountsCallback`.

Partially revert commit 6960e456.

Removing the errant `<remove-node/>` *introduces* errors:

	  obj/Debug/monoandroid10.0/generated/src/LoadAccountsFix.LoadAccountsCallback.cs(10,72): error CS0535: 'LoadAccountsCallback' does not implement interface member 'ITaskCompletedCallbackWithError.OnError(Object)'
	  obj/Debug/monoandroid10.0/generated/src/LoadAccountsFix.LoadAccountsCallback.cs(10,72): error CS0535: 'LoadAccountsCallback' does not implement interface member 'ITaskCompletedCallback.OnTaskCompleted(Object)'
	  obj/Debug/monoandroid10.0/generated/src/Com.Microsoft.Identity.Client.MultipleAccountPublicClientApplication.cs(10,127): error CS0535: 'MultipleAccountPublicClientApplication' does not implement interface member 'IMultipleAccountPublicClientApplication.GetAccounts(IPublicClientApplicationLoadAccountsCallback)'

Fix these errors by adding partial class declarations to implement
the missing interface methods.

This allows `src/bindings/Microsoft.Identity.Client.XamarinAndroid.AndroidX`
to build, and fixes the original CS0246 errors in `Bogdan.TestApp`.

Then we hit our next issue:

	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:  error: package loadAccountsFix does not exist
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:    extends loadAccountsFix.LoadAccountsCallback
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(21,7): javac error JAVAC0000:  error: cannot find symbol
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(21,7): javac error JAVAC0000:            if (getClass () == MainActivity_MultipleAccountApplicationCurrentAccountCallback.class)
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(21,7): javac error JAVAC0000:   symbol:   method getClass()
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(21,7): javac error JAVAC0000:   location: class MainActivity_MultipleAccountApplicationCurrentAccountCallback

The cause of this error is that `LoadAccountsCallback.jar` is bad;
specifically, it doesn't conform to Java expectations.

Normally, `.jar` files are structured such that package names become
directories within the `.jar`, and the Java class name is used as the
filename in the `.jar`, with a `.class` suffix.

`LoadAccountsCallback.jar` contains:

	$ jar tf LoadAccountsCallback.jar
	META-INF/
	META-INF/MANIFEST.MF
	LoadAccountsCallback.class

It *should* contain:

	$ jar tf LoadAccountsCallback.jar
	META-INF/
	META-INF/MANIFEST.MF
	loadAccountsFix/LoadAccountsCallback.class

When (manually) fixed to have the correct structure, we then hit
our next failure:

	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:  error: cannot access LoadAccountsCallback
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:    extends loadAccountsFix.LoadAccountsCallback
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:   bad class file: obj/Debug/lp/0/jl/LoadAccountsCallback.jar(loadAccountsFix/LoadAccountsCallback.class)
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:     class file has wrong version 55.0, should be 52.0
	…/MainActivity_MultipleAccountApplicationCurrentAccountCallback.java(5,25): javac error JAVAC0000:     Please remove or make sure it appears in the correct subdirectory of the classpath.

Fix this by *removing* `LoadAccountsCallback.jar`, and instead
*create it* as part of the build system; see
`src/bindings/Microsoft.Identity.Client.XamarinAndroid.AndroidX/Directory.Build.targets`.
The "fun" part is that to build `LoadAccountsCallback.java`, we need
`.jar` files for dependencies, but we only have `.aar` files.
Square this circle by using the `<Unzip/>` task from Xamarin.Android
to extract the `.aar` files into a temp folder, copy out `classes.jar`
into a "well known location", then use that well-known location to
build `LoadAccountsCallback.java`.  Once built -- with the appropriate
`javac -source 1.8 -target 1.8` parameters -- we can then use `jar`
to produce `LoadAccountsCallback.jar`.